### ISSUE TITLE
Background Music Not Working

### ISSUE THREAD

**Issue by CaptDrake** [Shakz76/Eazy-Hax-RetroPie-Toolkit#13]
I installed the Background Music script using the built-in installer, but it doesn't seem to be playing music. Confirmed that volume was set both on TV and within the tool itself. 

Running the latest version of Retropie (4.5.1).

**Comment by Korkman** [comment]
Found that this pull was bad:

https://github.com/Shakz76/Eazy-Hax-RetroPie-Toolkit/commit/3d1c03e119de03d3181ebd23a994d8a2f3318e5b

It "fixed" the name of emulationstation in a bad way: the linux kernel truncates the command name to 15 characters (plus null)., therefore "emulationstatio" is the correct value to compare against, unless the linux kernel changes this behavior. Revert the changes and it works as expected.

**Comment by CaptDrake** [comment]
Yep, that fixed the issue. I really appreciate your help.
