### ISSUE TITLE
Expand to External NTFS Drive

### ISSUE THREAD

**Issue by almulder** [Shakz76/Eazy-Hax-RetroPie-Toolkit#5]
I have the most current version, 121 of your scripts. I am trying to use "Expand to External NTFS Drive" it go and does it thing I pull the usb added 1 rom to the roms/nes folder to test with. plug it back it back in and power up the raspberry and near the end of ES loading it throws an error. 

emulationstation: /home/pi/RetroPie-Setup/tmp/build/emulationstation/es-core/src/rescources/Font.cpp:17: Font::FontFace::FontFace(resourceData&&, int): Assertion '!err' failed. 
Aborted

then goes to the command line.

Now if I unplug the usb and reboot it goes into es fine, but using the usb i get the error every time.

**Comment by Shakz76** [comment]
Man that's just weird. The only directory the script touches is roms. I am not saying you did anything wrong just trying to figure the cause but have you done any source based updates to emulation station? I am guessing some configs changed somewhere. While I have you....would you even use the detachable function or just looking for an easy way to expand rom storage?

**Comment by almulder** [comment]
Wow sorry. looks like this was all due to a bad gamelist.xml file. Sowwy to waste your time. (atleast i figured it out)

**Comment by Shakz76** [comment]
all good...glad you got it sorted out man :-)
